### ISSUE TITLE
Good point on disks flag

### ISSUE THREAD

**Issue by ryuheechul** [jmarceli/test-cloud-init-vagrant#1]
_sorry, this is not really an "issue"_

Hey @jmarceli, thanks for [your article](https://www.grzegorowski.com/how-to-test-cloud-init-locally-with-vagrant), that solved my biggest mystery of why cloud-init didn't work with Vagrant.

I also filed [a PR](https://github.com/hashicorp/vagrant/pull/12104) to correct the documentation on this as you pointed it out that it's not reflected in the page. Hopefully more people discover this useful information 🤞🏼

**Comment by jmarceli** [comment]
Hi @ryuheechul this is the best issue I've ever had :) thanks for sharing I'm glad you found my article useful.
