### ISSUE TITLE
About loading envs

### ISSUE THREAD

**Issue by ryuheechul** [jmarceli/test-cloud-init-vagrant#2]
This repo doesn't come with `.env` file, which should contain, `VAGRANT_EXPERIMENTAL="cloud_init,disks"` which is explained in the article but could be mentioned in the repo, too, I think.

Also [this line](https://github.com/jmarceli/test-cloud-init-vagrant/blob/30a210805ce6c9e6e942c084041d5bd554b3db5e/Vagrantfile#L2) doesn't explain that it requires installing [a plugin](https://github.com/gosuri/vagrant-env), which I think explaining a bit would be helpful for beginners.

Another approach would be guiding `VAGRANT_EXPERIMENTAL="cloud_init,disks" vagrant up` instead.

Let me know what you think!

**Comment by jmarceli** [comment]
Thanks for pointing that out. I will update README.md file
